### PR TITLE
Add space before -l when generating command line

### LINKED ISSUE #284: racket-raco-test appends flag to racket path
Unfortunately `racket-raco-test` does not work as the flag `-l `is appended to the racket path.

```racket
/home/pmatos/INSTALLS/racket-6.10.1/bin/racket-l: No such file or directory
```

### PR DESCRIPTION
**Pull request by pmatos**
Fixes #284.

### CODE REVIEW

**Comment by pmatos** [comment]
@greghendershott is there a reason you can't merge this?

**Comment by greghendershott** [comment]
No good reason, just that I've been swamped and am behind reviewing PRs overall. I'm sorry and I'll try to catch up this weekend.

**Comment by pmatos** [comment]
No problem. :) Just trying to ensure it hadn't been forgotten. Thanks for your time!

**Comment by greghendershott** [comment]
Merged -- thank you!

**Pull request merged**
