### PR TITLE
Customization of unicode input method

### PR DESCRIPTION
**Pull request by bkc39**
Make the keybindings customizable via user-defined functions. Bindings inherit from `racket-unicode`

this should be tested as some of the code and docs were written by LLM, but it seems to work well enough for me

```elisp
(racket-custom-unicode-add-tweaks!
 (remove-suffix " ")
 (prefix-with "\\"))
(racket-custom-unicode-input-method-enable) ;; now \alpha maps to unicode alpha
```

Partially addresses #718

### CODE REVIEW

**Comment by greghendershott** [comment]
Unfortunately for license provenance reasons I'm unable to merge code sourced by an LLM.

I understand some (maybe even most?) you wrote by hand. That's why I wanted to mention this as soon as I noticed -- before you put much more work into it.  :disappointed: 

I really appreciate you taking the time to work on this. I feel badly. I'm definitely not suggesting you did anything wrong; just that it wouldn't work for this project.

---

In any case, I really did have in mind what I'd mentioned: Borrowing the agda2-input code almost verbatim. Because I've grown to appreciate its approach. Also the provenance would be clear.

[In fact: I wonder if we could recommend people install the agda package; it doesn't seem to depend on other packages, so it's pretty light. And we'd literally use its code, that way. And we could supply an initial configuration of it, equivalent to our status quo. Something like that.]

**Comment by greghendershott** [comment]
p.s. Since I seem to have particular ideas about this, maybe it would be better if I worked on this, at least to do an overall "first draft" commit? And then I'd welcome your review/contributions against that baseline, if you wanted?

It doesn't seem fair to have you try to chase down some idea if I'm not being clear about it. And if you want to contribute using some approaches, but not anothers, of course that's valid, its up to you not me!

**Comment by bkc39** [comment]
> I really appreciate you taking the time to work on this. I feel badly. I'm definitely not suggesting you did anything wrong; just that it wouldn't work for this project.

No worries. I would say maybe add this to your contributing page. I do nearly all programming with some LLM assistance these days and I'm sure I'm not the only one. If this is going to be your policy I would make that more clear to potential contributors. The thought that there might be some license issues never occurred to me.

**Comment by bkc39** [comment]
> p.s. Since I seem to have particular ideas about this, maybe it would be better if I worked on this, at least to do an overall "first draft" commit? And then I'd welcome your review/contributions against that baseline, if you wanted?
> 
> It doesn't seem fair to have you try to chase down some idea if I'm not being clear about it. And if you want to contribute using some approaches, but not anothers, of course that's valid, its up to you not me!

Yea this seems good. I'll keep an eye out.

**Pull request closed without merging**
