### PR TITLE
Use "setin " instead of "in " to produce ∈.

### PR DESCRIPTION
**Pull request by soegaard**
Since "in" is both a very commonly used word and a common suffix of english words, 
the replacement "in " to "∈" quickly becomes annoying when writing normal text when 
when the `racket-unicode-input-method` is enabled.

I propose to replace "in " with "setin " that way the  it is not neccessary to
keep toggling `racket-unicode-input-method` on-and-off again.

The downside is that most users will expect "in " since "\in" is used in TeX.

### CODE REVIEW

**Comment by greghendershott** [comment]
Thank you for the PR.

This is one of the few parts of Racket Mode I don't normally use/"dog-food" myself (or even input methods in Emacs, generally). 

So although I trust your judgment, I can't offer any good second opinion.

From issue #393 I see a few people who might care so I'll `@` them: @emacsomancer, @stchang, @capfredf 

Assuming they're on board, or don't chime in within a day or two, I'll go ahead and merge.

Thanks again!

**Comment by capfredf** [comment]
+1 for this change. FWIW, I turn off the unicode input by default.  Nowadays, it is more likely I turn it on when I am writing a org document and those symbols are needed. :stuck_out_tongue_winking_eye:

**Comment by sorawee** [comment]
I've never used `racket-unicode-input-method`, but I used something similar for Lean-mode. In Lean-mode however, we need to explicitly start the unicode character with `\`, similar to how LaTeX works. Couldn't the same be done here? It would also allow us to write `\in`.

**Comment by bestlem** [comment]
@sorawee If you use company then the backend company-math-symbols-unicode workls like you suggest - however I don't know if it does all the things the racket addition does, it at least does the greek alphabet.

**Comment by capfredf** [comment]
agda-mode also uses the same approach as lean-mode does.

**Comment by greghendershott** [comment]
There are probably as many strategies and preferences for this kind of thing as there are Emacs users. :)

The `quail` / input-method approach is (IIUC):

- You type the characters. They are shown underlined while they match a substitution rule.
- Keep typing to accept.
- Or, type <kbd>C-\\</kbd> twice to toggle the input-method off and on, which cancels matching.

So you _could_ type <kbd>in</kbd> followed by <kbd>C-\ C-\\</kbd> to get plain "in" instead of "∈".  (That's probably even fewer keystrokes than typing <kbd>setin</kbd> as in this PR, depending on how you count keystrokes?)

Whether this `quail` / input-method style is more or less convenient than always needing to type a prefix like `\` ... I suppose depends on the person, and even on the particular thing they're writing from time to time?  I don't have any strong opinions anyway because I don't usually need this.

---

I suppose one thing we could do is define some var with the things most relevant to Racket -- such as the Turnstile symbols, but maybe not things like the greek letters or double-struck letters (𝔸).

And then that var might be handy for people who want to configure some other approach (like using a `\` prefix with an auto-completion framework, or whatever).

**Comment by greghendershott** [comment]
@soegaard If you don't want to use "the `C-\` trick" and still want to change "in" to "setin", I'm still happy to merge this PR.

**Comment by greghendershott** [comment]
p.s. I peeked at `agda-mode` and it looks like they also use `quail` / input-method. The thing is, [they have a `defcustom` which lets you tweak all of the "labels"; the default prepends `\`](https://github.com/jwiegley/agda-mode/blob/master/agda-input.el#L142).

So -- apart from probably just merging this PR as-is, i.e. fresh issue -- I could also look at adding such an option.

**Comment by soegaard** [comment]
Den man. 24. jan. 2022 kl. 16.59 skrev Greg Hendershott <
***@***.***>:

> @soegaard <https://github.com/soegaard> If you don't want to use "the C-\
> trick" and still want to change "in" to "setin", I'm still happy to merge
> this PR.
>
I'd like that.

Overall I am quite happy with how  racket-unicode-input-method  works.
(Except for the "in" case).

The quail / input-method approach is (IIUC):
>
>    - You type the characters. They are shown underlined while they match
>    a substitution rule.
>
>
>    - Keep typing to accept.
>
>
>    - Or, type C-\ twice to toggle the input-method off and on, which
>    cancels matching.
>
> That's very precise.

So you *could* type in followed by C-\ C-\ to get plain "in" instead of "∈".
> (That's probably even fewer keystrokes than typing setin as in this PR,
> depending on how you count keystrokes?)


The problem here is that  "in" is so common both as a word and as a suffix
that it ruins the flow in my writing.
    Examples:    in, join, win, bin, sin (sinus), main, thin, spin etc.

Even in mathematical text I write the word "in" more often than I need ∈.

For the other abbreviations like  alpha, beta, etc, there are no problems -
they aren't common suffixes.
Therefore I think the current system with no prefix \ works fine.

/Jens Axel

**Comment by stchang** [comment]
Sorry for not responding earlier, but I get tripped up by the issue in this pr all the time so I support the merge!

**Pull request merged**
